//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice2903.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvaibleIng
    {
        public int DishId { get; set; }
        public string DishName { get; set; }
        public int IngId { get; set; }
        public string IngName { get; set; }
        public double Quantity { get; set; }
        public double AvailableCount { get; set; }
    }
}
