//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice2903.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngredientOfStage
    {
        public int Id { get; set; }
        public Nullable<int> CookingStageId { get; set; }
        public Nullable<int> IngredientId { get; set; }
        public Nullable<double> Quantity { get; set; }
    
        public virtual CookingStage CookingStage { get; set; }
        public virtual Ingredient Ingredient { get; set; }
    }
}
